#include <HCSR04.h>

/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/f8ff560b-b6b0-4fa8-b7f0-13c0912d8767

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String status;
  float light;
  CloudLight lED;
  CloudLength distance;
  bool present;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <HCSR04.h>
HCSR04 hc(12,14);
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);
  pinMode(0, OUTPUT);
  pinMode(A0, INPUT);
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here
  Serial.println(hc.dist());
  light = analogRead(A0);
  distance = hc.dist();
  Serial.println(light);
  delay(100);
  if (distance > 100) present = false;
  else present = true;
  status = "";
}






/*
  Since LED is READ_WRITE variable, onLEDChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLEDChange() {
  // Add your code here to act upon LED change
  if (lED == 1) digitalWrite(0, HIGH);
  else digitalWrite(0, LOW);
}


/*
  Since Light is READ_WRITE variable, onLightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLightChange() {
  // Add your code here to act upon Light change
  light = analogRead(A0);
}





/*
  Since Present is READ_WRITE variable, onPresentChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPresentChange() {
  // Add your code here to act upon Present change
  if (present == true)
    status = "Desk in Use";
  else status = "Desk Not in Use";
}


/*
  Since Status is READ_WRITE variable, onStatusChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onStatusChange() {
  // Add your code here to act upon Status change
}
