:Author: PANAV
:Email:
:Date: 01/12/2022
:Revision: version#
:License: Public Domain

= Project: DESKIE

This Project integrated Whsatsapp API, with the powerful and capable Arduino IoT platform.
You can configure this project to be able to control your gadgets or sense surrounding from anywhere in the world.
Also includes Updates and alerts over your Whatsapp Number

== Step 1: Installation
Unzip the Source Code Zip
Configure your Arduino IOT Dashboard
Set up your whatsapp API
Set your Wi-fi Access point Credentials

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── Deskie.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact: 

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10       
| L1 | Red LED        | 2345-asdf   | 5        
| A1 | Arduino Zero   | ABX00066    | 1        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
