// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "89f43d16-d8ae-4d9c-9de1-5c908ff1978b";
#define SSID "Panavpalak"
#define PASS "22101982"
#define DEVICE_KEY "K0KMIKD34WSOJ0FCTSKE"

void onStatusChange();
void onLEDChange();
void onPresentChange();

String status;
float light;
CloudLight lED;
CloudLength distance;
bool present;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(status, READWRITE, ON_CHANGE, onStatusChange, 1);
  ArduinoCloud.addProperty(light, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(lED, READWRITE, ON_CHANGE, onLEDChange);
  ArduinoCloud.addProperty(distance, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(present, READWRITE, ON_CHANGE, onPresentChange, 1);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
